# Generated by Django 3.2.18 on 2023-06-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_ticket',
            name='bookid',
        ),
    ]
